### PR TITLE
Validate cron node

### PR DESCRIPTION
**Pull request by luissajunior**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
dojot/dojot#1141

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

### CODE REVIEW

**Comment by mprevide** [comment]
- Fix link with issue  to dojot/dojot#1141
- Remove commits for others issues

**Comment by mprevide** [comment]
Please, create a PR to development!

**Comment by mprevide** [comment]
@luissajunior

**Review by mprevide — APPROVED** [review]
Don't forget to create a PR to development!

**Comment by luissajunior** [comment]
> Don't forget to create a PR to development!

Created! dojot/flowbroker#306

**Review by thiagodpf — APPROVED** [review]
:+1:

**Pull request merged**
